task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/zju_mocap_exp/latent_xyzc_313.yaml'

train_dataset_module: 'lib.datasets.light_stage.multi_view_dataset_genebody'
train_dataset_path: 'lib/datasets/light_stage/multi_view_dataset_genebody.py'
test_dataset_module: 'lib.datasets.light_stage.multi_view_dataset_genebody'
test_dataset_path: 'lib/datasets/light_stage/multi_view_dataset_genebody.py'

train_dataset:
    data_root: 'data/genebody'
    human: 'amanda'
    ann_file: 'data/genebody/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/genebody'
    human: 'amanda'
    ann_file: 'data/genebody/annots.npy'
    split: 'test'
    eval_skip: 5

# data options
H: 512
W: 512
ratio: 1.
training_view: [1,13,25,37]
num_train_frame: 75 
smpl: 'smpl'
vertices: 'vertices'
params: 'params'
big_box: True
frame_name_start: 45


eval_whole_img: True

nv: 10475
